// Code generated by protoc-gen-go.
// source: Talk.proto
// DO NOT EDIT!

/*
Package main is a generated protocol buffer package.

It is generated from these files:
	Talk.proto

It has these top-level messages:
	Person
	AddressBook
*/
package main

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Person_PhoneType int32

const (
	Person_MOBILE Person_PhoneType = 0
	Person_HOME   Person_PhoneType = 1
	Person_WORK   Person_PhoneType = 2
)

var Person_PhoneType_name = map[int32]string{
	0: "MOBILE",
	1: "HOME",
	2: "WORK",
}
var Person_PhoneType_value = map[string]int32{
	"MOBILE": 0,
	"HOME":   1,
	"WORK":   2,
}

func (x Person_PhoneType) Enum() *Person_PhoneType {
	p := new(Person_PhoneType)
	*p = x
	return p
}
func (x Person_PhoneType) String() string {
	return proto.EnumName(Person_PhoneType_name, int32(x))
}
func (x *Person_PhoneType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(Person_PhoneType_value, data, "Person_PhoneType")
	if err != nil {
		return err
	}
	*x = Person_PhoneType(value)
	return nil
}
func (Person_PhoneType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

type Person struct {
	Name             *string               `protobuf:"bytes,1,req,name=name" json:"name,omitempty"`
	Id               *int64                `protobuf:"varint,2,req,name=id" json:"id,omitempty"`
	Email            *string               `protobuf:"bytes,3,req,name=email" json:"email,omitempty"`
	Value1           *float64              `protobuf:"fixed64,4,req,name=value1" json:"value1,omitempty"`
	Phones           []*Person_PhoneNumber `protobuf:"bytes,5,rep,name=phones" json:"phones,omitempty"`
	XXX_unrecognized []byte                `json:"-"`
}

func (m *Person) Reset()                    { *m = Person{} }
func (m *Person) String() string            { return proto.CompactTextString(m) }
func (*Person) ProtoMessage()               {}
func (*Person) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Person) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *Person) GetId() int64 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *Person) GetEmail() string {
	if m != nil && m.Email != nil {
		return *m.Email
	}
	return ""
}

func (m *Person) GetValue1() float64 {
	if m != nil && m.Value1 != nil {
		return *m.Value1
	}
	return 0
}

func (m *Person) GetPhones() []*Person_PhoneNumber {
	if m != nil {
		return m.Phones
	}
	return nil
}

type Person_PhoneNumber struct {
	Number           *string           `protobuf:"bytes,1,req,name=number" json:"number,omitempty"`
	Type             *Person_PhoneType `protobuf:"varint,2,req,name=type,enum=main.Person_PhoneType" json:"type,omitempty"`
	XXX_unrecognized []byte            `json:"-"`
}

func (m *Person_PhoneNumber) Reset()                    { *m = Person_PhoneNumber{} }
func (m *Person_PhoneNumber) String() string            { return proto.CompactTextString(m) }
func (*Person_PhoneNumber) ProtoMessage()               {}
func (*Person_PhoneNumber) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

func (m *Person_PhoneNumber) GetNumber() string {
	if m != nil && m.Number != nil {
		return *m.Number
	}
	return ""
}

func (m *Person_PhoneNumber) GetType() Person_PhoneType {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return Person_MOBILE
}

type AddressBook struct {
	People           []*Person `protobuf:"bytes,1,rep,name=people" json:"people,omitempty"`
	XXX_unrecognized []byte    `json:"-"`
}

func (m *AddressBook) Reset()                    { *m = AddressBook{} }
func (m *AddressBook) String() string            { return proto.CompactTextString(m) }
func (*AddressBook) ProtoMessage()               {}
func (*AddressBook) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *AddressBook) GetPeople() []*Person {
	if m != nil {
		return m.People
	}
	return nil
}

func init() {
	proto.RegisterType((*Person)(nil), "main.Person")
	proto.RegisterType((*Person_PhoneNumber)(nil), "main.Person.PhoneNumber")
	proto.RegisterType((*AddressBook)(nil), "main.AddressBook")
	proto.RegisterEnum("main.Person_PhoneType", Person_PhoneType_name, Person_PhoneType_value)
}

var fileDescriptor0 = []byte{
	// 264 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x64, 0x90, 0xcd, 0x4a, 0xc3, 0x40,
	0x14, 0x85, 0xcd, 0x4f, 0x83, 0xbd, 0xa9, 0x25, 0xce, 0x42, 0x06, 0xe9, 0xa2, 0x14, 0x17, 0x01,
	0x21, 0xd0, 0xbe, 0x81, 0x91, 0x82, 0xa2, 0x35, 0x41, 0x0a, 0xae, 0x13, 0x73, 0xd1, 0xd0, 0xf9,
	0x09, 0x99, 0x44, 0xe8, 0xc3, 0xfa, 0x2e, 0xde, 0x89, 0x22, 0x81, 0xee, 0xce, 0xe1, 0x0c, 0xdf,
	0x39, 0x73, 0x01, 0xf6, 0x85, 0x38, 0x24, 0x4d, 0xab, 0x3b, 0xcd, 0x7c, 0x59, 0xd4, 0x6a, 0xf5,
	0xed, 0x40, 0x90, 0x63, 0x6b, 0xb4, 0x62, 0x33, 0xf0, 0x55, 0x21, 0x91, 0x3b, 0x4b, 0x37, 0x9e,
	0x32, 0x00, 0xb7, 0xae, 0xb8, 0x4b, 0xda, 0x63, 0x17, 0x30, 0x41, 0x7a, 0x2d, 0xb8, 0x37, 0x44,
	0x73, 0x08, 0xbe, 0x0a, 0xd1, 0xe3, 0x9a, 0xfb, 0xe4, 0x1d, 0x16, 0x43, 0xd0, 0x7c, 0x6a, 0x85,
	0x86, 0x4f, 0x96, 0x5e, 0x1c, 0x6e, 0x78, 0x62, 0xd1, 0xc9, 0x2f, 0x36, 0xc9, 0x6d, 0xf4, 0xd2,
	0xcb, 0x12, 0xdb, 0xeb, 0x7b, 0x08, 0x47, 0xd6, 0x82, 0xd4, 0xa0, 0xfe, 0x3a, 0x6f, 0xc0, 0xef,
	0x8e, 0x0d, 0x0e, 0xad, 0xf3, 0xcd, 0xd5, 0x29, 0x66, 0x4f, 0xe9, 0xea, 0x16, 0xa6, 0xff, 0x86,
	0x66, 0x06, 0xbb, 0x2c, 0x7d, 0x7c, 0xde, 0x46, 0x67, 0xec, 0x1c, 0xfc, 0x87, 0x6c, 0xb7, 0x8d,
	0x1c, 0xab, 0xde, 0xb2, 0xd7, 0xa7, 0xc8, 0xa5, 0xc7, 0xe1, 0x5d, 0x55, 0xb5, 0x68, 0x4c, 0xaa,
	0xf5, 0x81, 0x2d, 0x68, 0x2a, 0xea, 0x46, 0xd8, 0x5f, 0xda, 0xa9, 0xb3, 0x71, 0x47, 0xba, 0x86,
	0xc5, 0xbb, 0x96, 0x49, 0x49, 0x9b, 0x04, 0x96, 0x88, 0x46, 0x8b, 0xbe, 0xab, 0xa9, 0x5c, 0x1e,
	0x3f, 0xe8, 0x32, 0xe9, 0xe5, 0x08, 0x95, 0xdb, 0x23, 0x9a, 0x9f, 0x00, 0x00, 0x00, 0xff, 0xff,
	0x28, 0x34, 0xb2, 0xca, 0x52, 0x01, 0x00, 0x00,
}
